// Generated by scripts/generate-skin-data.mjs. Edit assets/skins/*/skin.json instead.
export const GENERATED_SKINS = [
  {
    "id": "robot",
    "name": "Robot",
    "eyeLayout": "dual",
    "flavor": "Mechanical lenses with tiny LED attitude.",
    "iris": "#42d9ff",
    "pupil": "#07111b",
    "eyeWhite": "#f4eadc",
    "outline": "#2a2d30",
    "accent": "#ffcc33",
    "irisSize": 34,
    "pupilSize": 38,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/robot/eyes/left-base.png",
      "rightBase": "assets/skins/robot/eyes/right-base.png",
      "thumbnail": "assets/skins/robot/thumbnail.png",
      "mask": "assets/skins/robot/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.129,
        "y": 0.329,
        "w": 0.267,
        "h": 0.342
      },
      "right": {
        "side": "right",
        "x": 0.604,
        "y": 0.329,
        "w": 0.267,
        "h": 0.342
      }
    },
    "ambientReactions": [
      "wide-stare",
      "confused",
      "eye-roll",
      "rapid-typing-focus",
      "suspicious",
      "restless",
      "spacing-out"
    ]
  },
  {
    "id": "cat",
    "name": "Cat",
    "eyeLayout": "dual",
    "flavor": "Soft fur, sharp focus, vertical pupils.",
    "iris": "#58d34f",
    "pupil": "#050806",
    "eyeWhite": "#f4eadc",
    "outline": "#3b3735",
    "accent": "#120e0c",
    "irisSize": 37,
    "pupilSize": 22,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/cat/eyes/left-base.png",
      "rightBase": "assets/skins/cat/eyes/right-base.png",
      "thumbnail": "assets/skins/cat/thumbnail.png",
      "mask": "assets/skins/cat/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.135,
        "y": 0.33,
        "w": 0.315,
        "h": 0.41
      },
      "right": {
        "side": "right",
        "x": 0.55,
        "y": 0.33,
        "w": 0.315,
        "h": 0.41
      }
    },
    "ambientReactions": [
      "suspicious",
      "look-left",
      "look-right",
      "sleepy-idle",
      "happy",
      "dreamy",
      "wink-left"
    ]
  },
  {
    "id": "manga-female",
    "name": "Manga Female",
    "eyeLayout": "dual",
    "flavor": "Big anime eyes with soft lashes.",
    "iris": "#9b68ee",
    "pupil": "#140d2d",
    "eyeWhite": "#f4eadc",
    "outline": "#d99a96",
    "accent": "#5b252b",
    "irisSize": 35,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/manga-female/eyes/left-base.png",
      "rightBase": "assets/skins/manga-female/eyes/right-base.png",
      "thumbnail": "assets/skins/manga-female/thumbnail.png",
      "mask": "assets/skins/manga-female/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.135,
        "y": 0.3,
        "w": 0.32,
        "h": 0.43
      },
      "right": {
        "side": "right",
        "x": 0.545,
        "y": 0.3,
        "w": 0.32,
        "h": 0.43
      }
    },
    "ambientReactions": [
      "happy",
      "shocked",
      "crying",
      "in-love",
      "dreamy",
      "laughing",
      "wink-right"
    ]
  },
  {
    "id": "dragon",
    "name": "Dragon",
    "eyeLayout": "dual",
    "flavor": "Ancient scales with a fiery slit gaze.",
    "iris": "#ff9f21",
    "pupil": "#090403",
    "eyeWhite": "#f4eadc",
    "outline": "#1d2a24",
    "accent": "#050403",
    "irisSize": 36,
    "pupilSize": 19,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/dragon/eyes/left-base.png",
      "rightBase": "assets/skins/dragon/eyes/right-base.png",
      "thumbnail": "assets/skins/dragon/thumbnail.png",
      "mask": "assets/skins/dragon/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.129,
        "y": 0.329,
        "w": 0.267,
        "h": 0.342
      },
      "right": {
        "side": "right",
        "x": 0.604,
        "y": 0.329,
        "w": 0.267,
        "h": 0.342
      }
    },
    "ambientReactions": [
      "angry",
      "furious",
      "suspicious",
      "dramatic-shock",
      "chaotic-stare",
      "look-down"
    ]
  },
  {
    "id": "cyberpunk-female",
    "name": "Cyberpunk Female",
    "eyeLayout": "dual",
    "flavor": "Neon makeup, chrome accents, and a sharp magenta gaze.",
    "iris": "#ff4fd8",
    "pupil": "#080510",
    "eyeWhite": "#f4eef6",
    "outline": "#292033",
    "accent": "#07040d",
    "irisSize": 34,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/cyberpunk-female/eyes/left-base.png",
      "rightBase": "assets/skins/cyberpunk-female/eyes/right-base.png",
      "thumbnail": "assets/skins/cyberpunk-female/thumbnail.png",
      "mask": "assets/skins/cyberpunk-female/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.145,
        "y": 0.3,
        "w": 0.32,
        "h": 0.36
      },
      "right": {
        "side": "right",
        "x": 0.535,
        "y": 0.3,
        "w": 0.32,
        "h": 0.36
      }
    },
    "ambientReactions": [
      "in-love",
      "starstruck",
      "suspicious",
      "restless",
      "wink-right",
      "dreamy",
      "panic"
    ]
  },
  {
    "id": "c-4po",
    "name": "C-4PO",
    "eyeLayout": "dual",
    "flavor": "Golden robot faceplate with warm lamp eyes.",
    "iris": "#ffb21a",
    "pupil": "#120900",
    "eyeWhite": "#fff0ba",
    "outline": "#c9962a",
    "accent": "#362000",
    "irisSize": 38,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/c-4po/eyes/left-base.png",
      "rightBase": "assets/skins/c-4po/eyes/right-base.png",
      "thumbnail": "assets/skins/c-4po/thumbnail.png",
      "mask": "assets/skins/c-4po/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.17,
        "y": 0.305,
        "w": 0.255,
        "h": 0.47
      },
      "right": {
        "side": "right",
        "x": 0.575,
        "y": 0.305,
        "w": 0.255,
        "h": 0.47
      }
    },
    "ambientReactions": [
      "wide-stare",
      "confused",
      "nervous",
      "rapid-typing-focus",
      "starstruck",
      "panic",
      "slow-blink"
    ]
  },
  {
    "id": "atlas",
    "name": "Atlas",
    "eyeLayout": "single",
    "flavor": "White robot faceplate with one cool blue lamp eye.",
    "iris": "#1ecbff",
    "pupil": "#020817",
    "eyeWhite": "#d8f8ff",
    "outline": "#dce8f2",
    "accent": "#102438",
    "irisSize": 40,
    "pupilSize": 28,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/atlas/eyes/left-base.png",
      "rightBase": "assets/skins/atlas/eyes/right-base.png",
      "thumbnail": "assets/skins/atlas/thumbnail.png",
      "mask": "assets/skins/atlas/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.345,
        "y": 0.19,
        "w": 0.31,
        "h": 0.62
      },
      "right": {
        "side": "right",
        "x": 0.345,
        "y": 0.19,
        "w": 0.31,
        "h": 0.62
      }
    },
    "ambientReactions": [
      "wide-stare",
      "look-up",
      "confused",
      "dreamy",
      "starstruck",
      "spacing-out",
      "slow-blink"
    ]
  },
  {
    "id": "panda",
    "name": "Panda",
    "eyeLayout": "dual",
    "flavor": "Soft panda mask with calm bamboo-green eyes.",
    "iris": "#67b84f",
    "pupil": "#101509",
    "eyeWhite": "#f4ffe8",
    "outline": "#f0f5e9",
    "accent": "#1c2018",
    "irisSize": 34,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/panda/eyes/left-base.png",
      "rightBase": "assets/skins/panda/eyes/right-base.png",
      "thumbnail": "assets/skins/panda/thumbnail.png",
      "mask": "assets/skins/panda/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.2,
        "y": 0.485,
        "w": 0.24,
        "h": 0.34
      },
      "right": {
        "side": "right",
        "x": 0.56,
        "y": 0.485,
        "w": 0.24,
        "h": 0.34
      }
    },
    "ambientReactions": [
      "slow-blink",
      "sleepy",
      "happy",
      "dreamy",
      "look-left",
      "look-right",
      "in-love"
    ]
  },
  {
    "id": "d20-rpg",
    "name": "D20 RPG",
    "eyeLayout": "dual",
    "flavor": "Tabletop dice, parchment maps, and dungeon master focus.",
    "iris": "#3fcf7f",
    "pupil": "#100806",
    "eyeWhite": "#f2dec0",
    "outline": "#7b4f2b",
    "accent": "#2b170f",
    "irisSize": 32,
    "pupilSize": 28,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/d20-rpg/eyes/left-base.png",
      "rightBase": "assets/skins/d20-rpg/eyes/right-base.png",
      "thumbnail": "assets/skins/d20-rpg/thumbnail.png",
      "mask": "assets/skins/d20-rpg/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.155,
        "y": 0.326,
        "w": 0.279,
        "h": 0.29
      },
      "right": {
        "side": "right",
        "x": 0.569,
        "y": 0.326,
        "w": 0.278,
        "h": 0.29
      }
    },
    "ambientReactions": [
      "dramatic-shock",
      "wide-stare",
      "happy",
      "confused",
      "chaotic-stare",
      "panic",
      "starstruck"
    ]
  },
  {
    "id": "space-helmet",
    "name": "SpaceHelmet",
    "eyeLayout": "dual",
    "flavor": "Astronaut visor with cool cyan focus.",
    "iris": "#20d9ff",
    "pupil": "#020916",
    "eyeWhite": "#eaf7ff",
    "outline": "#d4e6ef",
    "accent": "#0d2032",
    "irisSize": 34,
    "pupilSize": 28,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/space-helmet/eyes/left-base.png",
      "rightBase": "assets/skins/space-helmet/eyes/right-base.png",
      "thumbnail": "assets/skins/space-helmet/thumbnail.png",
      "mask": "assets/skins/space-helmet/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.166,
        "y": 0.302,
        "w": 0.263,
        "h": 0.353
      },
      "right": {
        "side": "right",
        "x": 0.572,
        "y": 0.302,
        "w": 0.263,
        "h": 0.353
      }
    },
    "ambientReactions": [
      "wide-stare",
      "dreamy",
      "spacing-out",
      "starstruck",
      "look-up",
      "slow-blink"
    ]
  },
  {
    "id": "classic-googly",
    "name": "Classic Googly",
    "eyeLayout": "dual",
    "flavor": "Clean toy rings with bright playful eyes.",
    "iris": "#1e88ff",
    "pupil": "#050505",
    "eyeWhite": "#fffaf0",
    "outline": "#f2f2f2",
    "accent": "#d13b2f",
    "irisSize": 30,
    "pupilSize": 42,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/classic-googly/eyes/left-base.png",
      "rightBase": "assets/skins/classic-googly/eyes/right-base.png",
      "thumbnail": "assets/skins/classic-googly/thumbnail.png",
      "mask": "assets/skins/classic-googly/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.127,
        "y": 0.24,
        "w": 0.316,
        "h": 0.5
      },
      "right": {
        "side": "right",
        "x": 0.557,
        "y": 0.24,
        "w": 0.316,
        "h": 0.5
      }
    },
    "ambientReactions": [
      "happy",
      "laughing",
      "cross-eyed",
      "dizzy",
      "wink-left",
      "wink-right",
      "chaotic-stare"
    ]
  },
  {
    "id": "detective-noir",
    "name": "Detective Noir",
    "eyeLayout": "dual",
    "flavor": "Fedora shadows with a warm suspicious stare.",
    "iris": "#c28a3a",
    "pupil": "#120b04",
    "eyeWhite": "#f1dfbd",
    "outline": "#2d2118",
    "accent": "#0a0705",
    "irisSize": 31,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/detective-noir/eyes/left-base.png",
      "rightBase": "assets/skins/detective-noir/eyes/right-base.png",
      "thumbnail": "assets/skins/detective-noir/thumbnail.png",
      "mask": "assets/skins/detective-noir/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.197,
        "y": 0.368,
        "w": 0.248,
        "h": 0.236
      },
      "right": {
        "side": "right",
        "x": 0.563,
        "y": 0.368,
        "w": 0.248,
        "h": 0.236
      }
    },
    "ambientReactions": [
      "suspicious",
      "peek",
      "look-left",
      "look-right",
      "slow-blink",
      "restless"
    ]
  },
  {
    "id": "one-eye",
    "name": "One Eye",
    "eyeLayout": "single",
    "flavor": "Single cyclops opening with a curious lime stare.",
    "iris": "#b7ff35",
    "pupil": "#050806",
    "eyeWhite": "#f2ffe8",
    "outline": "#58b55f",
    "accent": "#33185d",
    "irisSize": 29,
    "pupilSize": 32,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/one-eye/eyes/left-base.png",
      "rightBase": "assets/skins/one-eye/eyes/right-base.png",
      "thumbnail": "assets/skins/one-eye/thumbnail.png",
      "mask": "assets/skins/one-eye/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.15,
        "y": 0.17,
        "w": 0.7,
        "h": 0.66
      },
      "right": {
        "side": "right",
        "x": 0.15,
        "y": 0.17,
        "w": 0.7,
        "h": 0.66
      }
    },
    "ambientReactions": [
      "wide-stare",
      "confused",
      "dizzy",
      "happy",
      "suspicious",
      "spacing-out",
      "wink-left"
    ]
  },
  {
    "id": "tibetan-monk",
    "name": "Tibetan Monk",
    "eyeLayout": "dual",
    "flavor": "Warm robes with a calm meditative gaze.",
    "iris": "#7f5634",
    "pupil": "#0b0806",
    "eyeWhite": "#f4eadc",
    "outline": "#9b5535",
    "accent": "#3d2018",
    "irisSize": 31,
    "pupilSize": 31,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/tibetan-monk/eyes/left-base.png",
      "rightBase": "assets/skins/tibetan-monk/eyes/right-base.png",
      "thumbnail": "assets/skins/tibetan-monk/thumbnail.png",
      "mask": "assets/skins/tibetan-monk/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.178,
        "y": 0.35,
        "w": 0.284,
        "h": 0.189
      },
      "right": {
        "side": "right",
        "x": 0.538,
        "y": 0.35,
        "w": 0.284,
        "h": 0.189
      }
    },
    "ambientReactions": [
      "slow-blink",
      "sleepy-idle",
      "look-down",
      "dreamy",
      "idle-long",
      "spacing-out"
    ]
  },
  {
    "id": "alien",
    "name": "Alien",
    "eyeLayout": "dual",
    "flavor": "Bioluminescent skin with an uncanny teal stare.",
    "iris": "#48eed8",
    "pupil": "#020809",
    "eyeWhite": "#dfe8e5",
    "outline": "#627f77",
    "accent": "#142427",
    "irisSize": 36,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/alien/eyes/left-base.png",
      "rightBase": "assets/skins/alien/eyes/right-base.png",
      "thumbnail": "assets/skins/alien/thumbnail.png",
      "mask": "assets/skins/alien/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1,
        "y": 0.285,
        "w": 0.325,
        "h": 0.425
      },
      "right": {
        "side": "right",
        "x": 0.575,
        "y": 0.285,
        "w": 0.325,
        "h": 0.425
      }
    },
    "ambientReactions": [
      "wide-stare",
      "confused",
      "dizzy",
      "cross-eyed",
      "peek",
      "stoned",
      "spacing-out"
    ]
  },
  {
    "id": "hacker",
    "name": "Hacker",
    "eyeLayout": "dual",
    "flavor": "Dark hood, terminal glow, and sharp focus.",
    "iris": "#58ff37",
    "pupil": "#010502",
    "eyeWhite": "#e5e1d8",
    "outline": "#2a2f2b",
    "accent": "#070a09",
    "irisSize": 31,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/hacker/eyes/left-base.png",
      "rightBase": "assets/skins/hacker/eyes/right-base.png",
      "thumbnail": "assets/skins/hacker/thumbnail.png",
      "mask": "assets/skins/hacker/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.11,
        "y": 0.27,
        "w": 0.38,
        "h": 0.39
      },
      "right": {
        "side": "right",
        "x": 0.51,
        "y": 0.27,
        "w": 0.38,
        "h": 0.39
      }
    },
    "ambientReactions": [
      "suspicious",
      "rapid-typing-focus",
      "look-left",
      "look-right",
      "nervous",
      "restless",
      "panic"
    ]
  },
  {
    "id": "anonymous",
    "name": "Anonymous",
    "eyeLayout": "dual",
    "flavor": "White mask, dark hood, and a quiet red stare.",
    "iris": "#ac1220",
    "pupil": "#050203",
    "eyeWhite": "#eee7d7",
    "outline": "#e1ddd1",
    "accent": "#1a1516",
    "irisSize": 30,
    "pupilSize": 32,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/anonymous/eyes/left-base.png",
      "rightBase": "assets/skins/anonymous/eyes/right-base.png",
      "thumbnail": "assets/skins/anonymous/thumbnail.png",
      "mask": "assets/skins/anonymous/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.155,
        "y": 0.315,
        "w": 0.31,
        "h": 0.28
      },
      "right": {
        "side": "right",
        "x": 0.535,
        "y": 0.315,
        "w": 0.31,
        "h": 0.28
      }
    },
    "ambientReactions": [
      "suspicious",
      "peek",
      "look-left",
      "look-right",
      "idle-long",
      "restless"
    ]
  },
  {
    "id": "ice-hockey",
    "name": "Jason",
    "eyeLayout": "dual",
    "flavor": "Frozen hockey mask with a blood-spattered stare.",
    "iris": "#b82022",
    "pupil": "#05090d",
    "eyeWhite": "#dcecf4",
    "outline": "#ccd7dd",
    "accent": "#101820",
    "irisSize": 30,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/ice-hockey/eyes/left-base.png",
      "rightBase": "assets/skins/ice-hockey/eyes/right-base.png",
      "thumbnail": "assets/skins/ice-hockey/thumbnail.png",
      "mask": "assets/skins/ice-hockey/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.188,
        "y": 0.348,
        "w": 0.239,
        "h": 0.224
      },
      "right": {
        "side": "right",
        "x": 0.573,
        "y": 0.348,
        "w": 0.239,
        "h": 0.224
      }
    },
    "ambientReactions": [
      "suspicious",
      "angry",
      "furious",
      "wide-stare",
      "shocked",
      "look-left"
    ]
  },
  {
    "id": "clown",
    "name": "Clown",
    "eyeLayout": "dual",
    "flavor": "Cartoon circus face with a bright playful stare.",
    "iris": "#ffcc2e",
    "pupil": "#100711",
    "eyeWhite": "#fff5df",
    "outline": "#ff9aa6",
    "accent": "#590913",
    "irisSize": 31,
    "pupilSize": 32,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/clown/eyes/left-base.png",
      "rightBase": "assets/skins/clown/eyes/right-base.png",
      "thumbnail": "assets/skins/clown/thumbnail.png",
      "mask": "assets/skins/clown/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.165,
        "y": 0.31,
        "w": 0.235,
        "h": 0.235
      },
      "right": {
        "side": "right",
        "x": 0.6,
        "y": 0.31,
        "w": 0.235,
        "h": 0.235
      }
    },
    "ambientReactions": [
      "happy",
      "laughing",
      "cross-eyed",
      "dizzy",
      "chaotic-stare",
      "shocked",
      "drunk"
    ]
  },
  {
    "id": "spy",
    "name": "Spy",
    "eyeLayout": "dual",
    "flavor": "Cartoon eyes peeking through newspaper cutouts.",
    "iris": "#4d6f8f",
    "pupil": "#080706",
    "eyeWhite": "#f6f0df",
    "outline": "#d8c7a9",
    "accent": "#4a3c2e",
    "irisSize": 30,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/spy/eyes/left-base.png",
      "rightBase": "assets/skins/spy/eyes/right-base.png",
      "thumbnail": "assets/skins/spy/thumbnail.png",
      "mask": "assets/skins/spy/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.164,
        "y": 0.237,
        "w": 0.269,
        "h": 0.219
      },
      "right": {
        "side": "right",
        "x": 0.565,
        "y": 0.237,
        "w": 0.272,
        "h": 0.219
      }
    },
    "ambientReactions": [
      "peek",
      "suspicious",
      "look-left",
      "look-right",
      "wide-stare",
      "wink-left",
      "restless"
    ]
  },
  {
    "id": "skeleton",
    "name": "Skeleton",
    "eyeLayout": "dual",
    "flavor": "Playful bone mask with deep skull sockets.",
    "iris": "#f0d36b",
    "pupil": "#07090c",
    "eyeWhite": "#f8f0dc",
    "outline": "#e8dcc2",
    "accent": "#5d5549",
    "irisSize": 32,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/skeleton/eyes/left-base.png",
      "rightBase": "assets/skins/skeleton/eyes/right-base.png",
      "thumbnail": "assets/skins/skeleton/thumbnail.png",
      "mask": "assets/skins/skeleton/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.161,
        "y": 0.209,
        "w": 0.294,
        "h": 0.433
      },
      "right": {
        "side": "right",
        "x": 0.544,
        "y": 0.209,
        "w": 0.285,
        "h": 0.43
      }
    },
    "ambientReactions": [
      "suspicious",
      "sleepy-idle",
      "shocked",
      "confused",
      "idle-long",
      "spacing-out"
    ]
  },
  {
    "id": "wizard",
    "name": "Wizard",
    "eyeLayout": "dual",
    "flavor": "Moonlit hat, silver brows, and a violet spellcaster gaze.",
    "iris": "#8f6bff",
    "pupil": "#090316",
    "eyeWhite": "#f2e3c5",
    "outline": "#7d5b46",
    "accent": "#2f1b16",
    "irisSize": 34,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/wizard/eyes/left-base.png",
      "rightBase": "assets/skins/wizard/eyes/right-base.png",
      "thumbnail": "assets/skins/wizard/thumbnail.png",
      "mask": "assets/skins/wizard/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.24,
        "y": 0.36,
        "w": 0.27,
        "h": 0.29
      },
      "right": {
        "side": "right",
        "x": 0.49,
        "y": 0.36,
        "w": 0.27,
        "h": 0.29
      }
    },
    "ambientReactions": [
      "dreamy",
      "starstruck",
      "slow-blink",
      "suspicious",
      "spacing-out",
      "wide-stare",
      "wink-right"
    ]
  },
  {
    "id": "cowboy",
    "name": "Cowboy",
    "eyeLayout": "dual",
    "flavor": "Dusty western hat with a curious frontier stare.",
    "iris": "#39b7a3",
    "pupil": "#130a04",
    "eyeWhite": "#fff4df",
    "outline": "#7a421d",
    "accent": "#2f1507",
    "irisSize": 32,
    "pupilSize": 30,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/cowboy/eyes/left-base.png",
      "rightBase": "assets/skins/cowboy/eyes/right-base.png",
      "thumbnail": "assets/skins/cowboy/thumbnail.png",
      "mask": "assets/skins/cowboy/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.17,
        "y": 0.28,
        "w": 0.34,
        "h": 0.44
      },
      "right": {
        "side": "right",
        "x": 0.49,
        "y": 0.28,
        "w": 0.34,
        "h": 0.44
      }
    },
    "ambientReactions": [
      "suspicious",
      "look-left",
      "look-right",
      "slow-blink",
      "wink-right",
      "restless"
    ]
  },
  {
    "id": "pumpkin-halloween",
    "name": "Pumpkin Halloween",
    "eyeLayout": "dual",
    "flavor": "Glowing jack-o-lantern mischief for spooky notes.",
    "iris": "#95ff24",
    "pupil": "#13020a",
    "eyeWhite": "#fff0bf",
    "outline": "#ff8a12",
    "accent": "#4d1104",
    "irisSize": 34,
    "pupilSize": 29,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/pumpkin-halloween/eyes/left-base.png",
      "rightBase": "assets/skins/pumpkin-halloween/eyes/right-base.png",
      "thumbnail": "assets/skins/pumpkin-halloween/thumbnail.png",
      "mask": "assets/skins/pumpkin-halloween/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.145,
        "y": 0.24,
        "w": 0.31,
        "h": 0.495
      },
      "right": {
        "side": "right",
        "x": 0.545,
        "y": 0.24,
        "w": 0.31,
        "h": 0.495
      }
    },
    "ambientReactions": [
      "chaotic-stare",
      "shocked",
      "laughing",
      "dizzy",
      "spacing-out",
      "wink-left"
    ]
  },
  {
    "id": "goblin",
    "name": "Goblin",
    "eyeLayout": "dual",
    "flavor": "Green fantasy trouble with a sneaky bright gaze.",
    "iris": "#d6b23a",
    "pupil": "#090704",
    "eyeWhite": "#efe7b8",
    "outline": "#527314",
    "accent": "#192606",
    "irisSize": 33,
    "pupilSize": 31,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/goblin/eyes/left-base.png",
      "rightBase": "assets/skins/goblin/eyes/right-base.png",
      "thumbnail": "assets/skins/goblin/thumbnail.png",
      "mask": "assets/skins/goblin/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.19,
        "y": 0.325,
        "w": 0.345,
        "h": 0.38
      },
      "right": {
        "side": "right",
        "x": 0.535,
        "y": 0.325,
        "w": 0.345,
        "h": 0.38
      }
    },
    "ambientReactions": [
      "hover-suspicious",
      "suspicious",
      "cross-eyed",
      "laughing",
      "peek",
      "restless"
    ]
  },
  {
    "id": "troll",
    "name": "Troll",
    "eyeLayout": "dual",
    "flavor": "Stone cave face with a heavy grumpy gaze.",
    "iris": "#6fd2ff",
    "pupil": "#040b10",
    "eyeWhite": "#e6eef2",
    "outline": "#4a5b60",
    "accent": "#151d20",
    "irisSize": 32,
    "pupilSize": 28,
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/troll/eyes/left-base.png",
      "rightBase": "assets/skins/troll/eyes/right-base.png",
      "thumbnail": "assets/skins/troll/thumbnail.png",
      "mask": "assets/skins/troll/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.23,
        "y": 0.305,
        "w": 0.245,
        "h": 0.315
      },
      "right": {
        "side": "right",
        "x": 0.585,
        "y": 0.305,
        "w": 0.245,
        "h": 0.315
      }
    },
    "ambientReactions": [
      "angry",
      "furious",
      "look-down",
      "sleepy",
      "slow-blink",
      "confused"
    ]
  }
] as const;

export const GENERATED_LAYERED_SKINS = new Set(["robot","cat","manga-female","dragon","cyberpunk-female","c-4po","atlas","panda","d20-rpg","space-helmet","classic-googly","detective-noir","one-eye","tibetan-monk","alien","hacker","anonymous","ice-hockey","clown","spy","skeleton","wizard","cowboy","pumpkin-halloween","goblin","troll"]);

export const GENERATED_SKIN_EYE_WINDOWS = Object.fromEntries(
  GENERATED_SKINS.map((skin) => [skin.id, skin.eyeWindows])
);

export const GENERATED_SKIN_AMBIENT_REACTIONS = Object.fromEntries(
  GENERATED_SKINS.map((skin) => [skin.id, skin.ambientReactions])
);
