// Generated by scripts/generate-skin-data.mjs. Edit assets/skins/*/skin.json instead.
export const GENERATED_SKINS = [
  {
    "id": "robot",
    "name": "Robot",
    "eyeLayout": "dual",
    "flavor": "Mechanical lenses with tiny LED attitude.",
    "iris": "#42d9ff",
    "pupil": "#07111b",
    "eyeWhite": "#f4eadc",
    "outline": "#2a2d30",
    "accent": "#ffcc33",
    "irisSize": 38,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/robot/eyes/left-base.png",
      "rightBase": "assets/skins/robot/eyes/right-base.png",
      "thumbnail": "assets/skins/robot/thumbnail.png",
      "mask": "assets/skins/robot/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1116,
        "y": 0.2852,
        "w": 0.3021,
        "h": 0.4295
      },
      "right": {
        "side": "right",
        "x": 0.5868,
        "y": 0.2852,
        "w": 0.3021,
        "h": 0.4295
      }
    },
    "ambientReactions": [
      "wide-stare",
      "confused",
      "eye-roll",
      "rapid-typing-focus",
      "suspicious",
      "restless",
      "spacing-out"
    ]
  },
  {
    "id": "cat",
    "name": "Cat",
    "eyeLayout": "dual",
    "flavor": "Soft fur, sharp focus, vertical pupils.",
    "iris": "#58d34f",
    "pupil": "#050806",
    "eyeWhite": "#f4ffe8",
    "outline": "#3b3735",
    "accent": "#120e0c",
    "irisSize": 44,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/cat/eyes/left-base.png",
      "rightBase": "assets/skins/cat/eyes/right-base.png",
      "thumbnail": "assets/skins/cat/thumbnail.png",
      "mask": "assets/skins/cat/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1285,
        "y": 0.2694,
        "w": 0.3134,
        "h": 0.4216
      },
      "right": {
        "side": "right",
        "x": 0.5586,
        "y": 0.2694,
        "w": 0.3134,
        "h": 0.4216
      }
    },
    "ambientReactions": [
      "suspicious",
      "look-left",
      "look-right",
      "sleepy-idle",
      "happy",
      "dreamy",
      "wink-left"
    ]
  },
  {
    "id": "manga-female",
    "name": "Manga Female",
    "eyeLayout": "dual",
    "flavor": "Bright manga eye openings with clean stylized pupils.",
    "iris": "#9b68ee",
    "pupil": "#140d2d",
    "eyeWhite": "#f3efe4",
    "outline": "#d99a96",
    "accent": "#5b252b",
    "irisSize": 68,
    "pupilSize": 30,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/manga-female/eyes/left-base.png",
      "rightBase": "assets/skins/manga-female/eyes/right-base.png",
      "thumbnail": "assets/skins/manga-female/thumbnail.png",
      "mask": "assets/skins/manga-female/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1026,
        "y": 0.3247,
        "w": 0.3078,
        "h": 0.4284
      },
      "right": {
        "side": "right",
        "x": 0.5868,
        "y": 0.3213,
        "w": 0.3061,
        "h": 0.4318
      }
    },
    "ambientReactions": [
      "happy",
      "shocked",
      "crying",
      "in-love",
      "dreamy",
      "laughing",
      "wink-right"
    ]
  },
  {
    "id": "dragon",
    "name": "Dragon",
    "eyeLayout": "dual",
    "flavor": "Ancient scales with a fiery slit gaze.",
    "iris": "#ff9f21",
    "pupil": "#090403",
    "eyeWhite": "#f4efe0",
    "outline": "#1d2a24",
    "accent": "#050403",
    "irisSize": 38,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/dragon/eyes/left-base.png",
      "rightBase": "assets/skins/dragon/eyes/right-base.png",
      "thumbnail": "assets/skins/dragon/thumbnail.png",
      "mask": "assets/skins/dragon/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.044,
        "y": 0.2649,
        "w": 0.3517,
        "h": 0.4656
      },
      "right": {
        "side": "right",
        "x": 0.6048,
        "y": 0.2649,
        "w": 0.3517,
        "h": 0.4656
      }
    },
    "ambientReactions": [
      "angry",
      "furious",
      "suspicious",
      "dramatic-shock",
      "chaotic-stare",
      "look-down"
    ]
  },
  {
    "id": "cyberpunk-female",
    "name": "Cyberpunk Female",
    "eyeLayout": "dual",
    "flavor": "Neon makeup, chrome accents, and a sharp magenta gaze.",
    "iris": "#ff4fd8",
    "pupil": "#080510",
    "eyeWhite": "#f4eef6",
    "outline": "#292033",
    "accent": "#07040d",
    "irisSize": 42,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/cyberpunk-female/eyes/left-base.png",
      "rightBase": "assets/skins/cyberpunk-female/eyes/right-base.png",
      "thumbnail": "assets/skins/cyberpunk-female/thumbnail.png",
      "mask": "assets/skins/cyberpunk-female/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1105,
        "y": 0.3608,
        "w": 0.2931,
        "h": 0.301
      },
      "right": {
        "side": "right",
        "x": 0.597,
        "y": 0.3596,
        "w": 0.2926,
        "h": 0.3021
      }
    },
    "ambientReactions": [
      "in-love",
      "starstruck",
      "suspicious",
      "restless",
      "wink-right",
      "dreamy",
      "panic"
    ]
  },
  {
    "id": "c-4po",
    "name": "C-4PO",
    "eyeLayout": "dual",
    "flavor": "Golden robot faceplate with warm lamp eyes.",
    "iris": "#ffb21a",
    "pupil": "#fff3a6",
    "eyeWhite": "#fff0ba",
    "outline": "#c9962a",
    "accent": "#362000",
    "irisSize": 44,
    "pupilSize": 24,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/c-4po/eyes/left-base.png",
      "rightBase": "assets/skins/c-4po/eyes/right-base.png",
      "thumbnail": "assets/skins/c-4po/thumbnail.png",
      "mask": "assets/skins/c-4po/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1573,
        "y": 0.3357,
        "w": 0.2824,
        "h": 0.5
      },
      "right": {
        "side": "right",
        "x": 0.562,
        "y": 0.3357,
        "w": 0.2824,
        "h": 0.5
      }
    },
    "ambientReactions": [
      "wide-stare",
      "confused",
      "nervous",
      "rapid-typing-focus",
      "starstruck",
      "panic",
      "slow-blink"
    ]
  },
  {
    "id": "atlas",
    "name": "Atlas",
    "eyeLayout": "single",
    "flavor": "White robot faceplate with one cool blue lamp eye.",
    "iris": "#1ecbff",
    "pupil": "#baf7ff",
    "eyeWhite": "#d8f8ff",
    "outline": "#dce8f2",
    "accent": "#102438",
    "irisSize": 44,
    "pupilSize": 24,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/atlas/eyes/left-base.png",
      "rightBase": "assets/skins/atlas/eyes/right-base.png",
      "thumbnail": "assets/skins/atlas/thumbnail.png",
      "mask": "assets/skins/atlas/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.345,
        "y": 0.19,
        "w": 0.31,
        "h": 0.62
      },
      "right": {
        "side": "right",
        "x": 0.345,
        "y": 0.19,
        "w": 0.31,
        "h": 0.62
      }
    },
    "ambientReactions": [
      "wide-stare",
      "look-up",
      "confused",
      "dreamy",
      "starstruck",
      "spacing-out",
      "slow-blink"
    ]
  },
  {
    "id": "panda",
    "name": "Panda",
    "eyeLayout": "dual",
    "flavor": "Soft panda mask with calm bamboo-green eyes.",
    "iris": "#67b84f",
    "pupil": "#101509",
    "eyeWhite": "#f4ffe8",
    "outline": "#f0f5e9",
    "accent": "#1c2018",
    "irisSize": 42,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/panda/eyes/left-base.png",
      "rightBase": "assets/skins/panda/eyes/right-base.png",
      "thumbnail": "assets/skins/panda/thumbnail.png",
      "mask": "assets/skins/panda/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1623,
        "y": 0.4307,
        "w": 0.2334,
        "h": 0.4295
      },
      "right": {
        "side": "right",
        "x": 0.6043,
        "y": 0.4307,
        "w": 0.2339,
        "h": 0.4295
      }
    },
    "ambientReactions": [
      "slow-blink",
      "sleepy",
      "happy",
      "dreamy",
      "look-left",
      "look-right",
      "in-love"
    ]
  },
  {
    "id": "d20-rpg",
    "name": "D20 DND",
    "eyeLayout": "dual",
    "flavor": "Tabletop dice, parchment maps, and dungeon master focus.",
    "iris": "#24c66f",
    "pupil": "#100806",
    "eyeWhite": "#f3e1be",
    "outline": "#8f5a2e",
    "accent": "#2b170f",
    "irisSize": 40,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/d20-rpg/eyes/left-base.png",
      "rightBase": "assets/skins/d20-rpg/eyes/right-base.png",
      "thumbnail": "assets/skins/d20-rpg/thumbnail.png",
      "mask": "assets/skins/d20-rpg/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1995,
        "y": 0.2627,
        "w": 0.2531,
        "h": 0.4532
      },
      "right": {
        "side": "right",
        "x": 0.5474,
        "y": 0.2638,
        "w": 0.2531,
        "h": 0.451
      }
    },
    "ambientReactions": [
      "dramatic-shock",
      "wide-stare",
      "happy",
      "confused",
      "chaotic-stare",
      "panic",
      "starstruck"
    ]
  },
  {
    "id": "space-helmet",
    "name": "SpaceHelmet",
    "eyeLayout": "dual",
    "flavor": "Astronaut visor with bright teal focus.",
    "iris": "#71d7d1",
    "pupil": "#020916",
    "eyeWhite": "#eaf7ff",
    "outline": "#d4e6ef",
    "accent": "#0d2032",
    "irisSize": 42,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/space-helmet/eyes/left-base.png",
      "rightBase": "assets/skins/space-helmet/eyes/right-base.png",
      "thumbnail": "assets/skins/space-helmet/thumbnail.png",
      "mask": "assets/skins/space-helmet/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1099,
        "y": 0.1811,
        "w": 0.3427,
        "h": 0.49
      },
      "right": {
        "side": "right",
        "x": 0.5474,
        "y": 0.1811,
        "w": 0.3427,
        "h": 0.49
      }
    },
    "ambientReactions": [
      "wide-stare",
      "dreamy",
      "spacing-out",
      "starstruck",
      "look-up",
      "slow-blink"
    ]
  },
  {
    "id": "classic-googly",
    "name": "Classic Googly",
    "eyeLayout": "dual",
    "flavor": "Clean toy rings with bright playful eyes.",
    "iris": "#1e88ff",
    "pupil": "#050505",
    "eyeWhite": "#fffaf0",
    "outline": "#f2f2f2",
    "accent": "#d13b2f",
    "irisSize": 38,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/classic-googly/eyes/left-base.png",
      "rightBase": "assets/skins/classic-googly/eyes/right-base.png",
      "thumbnail": "assets/skins/classic-googly/thumbnail.png",
      "mask": "assets/skins/classic-googly/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1764,
        "y": 0.2503,
        "w": 0.2176,
        "h": 0.4803
      },
      "right": {
        "side": "right",
        "x": 0.6065,
        "y": 0.2503,
        "w": 0.2176,
        "h": 0.4803
      }
    },
    "ambientReactions": [
      "happy",
      "laughing",
      "cross-eyed",
      "dizzy",
      "wink-left",
      "wink-right",
      "chaotic-stare"
    ]
  },
  {
    "id": "detective-noir",
    "name": "Detective Noir",
    "eyeLayout": "dual",
    "flavor": "Fedora shadows with a warm suspicious stare.",
    "iris": "#c28a3a",
    "pupil": "#120b04",
    "eyeWhite": "#f1dfbd",
    "outline": "#2d2118",
    "accent": "#0a0705",
    "irisSize": 40,
    "pupilSize": 17,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/detective-noir/eyes/left-base.png",
      "rightBase": "assets/skins/detective-noir/eyes/right-base.png",
      "thumbnail": "assets/skins/detective-noir/thumbnail.png",
      "mask": "assets/skins/detective-noir/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1635,
        "y": 0.4104,
        "w": 0.2694,
        "h": 0.2446
      },
      "right": {
        "side": "right",
        "x": 0.5676,
        "y": 0.4081,
        "w": 0.2706,
        "h": 0.2492
      }
    },
    "ambientReactions": [
      "suspicious",
      "peek",
      "look-left",
      "look-right",
      "slow-blink",
      "restless"
    ]
  },
  {
    "id": "one-eye",
    "name": "One Eye",
    "eyeLayout": "single",
    "flavor": "Single cyclops opening with a curious lime stare.",
    "iris": "#b7ff35",
    "pupil": "#050806",
    "eyeWhite": "#f2ffe8",
    "outline": "#58b55f",
    "accent": "#33185d",
    "irisSize": 44,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/one-eye/eyes/left-base.png",
      "rightBase": "assets/skins/one-eye/eyes/right-base.png",
      "thumbnail": "assets/skins/one-eye/thumbnail.png",
      "mask": "assets/skins/one-eye/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.2069,
        "y": 0.2694,
        "w": 0.5868,
        "h": 0.5242
      },
      "right": {
        "side": "right",
        "x": 0.2069,
        "y": 0.2694,
        "w": 0.5868,
        "h": 0.5242
      }
    },
    "ambientReactions": [
      "wide-stare",
      "confused",
      "dizzy",
      "happy",
      "suspicious",
      "spacing-out",
      "wink-left"
    ]
  },
  {
    "id": "tibetan-monk",
    "name": "Air Monk",
    "eyeLayout": "dual",
    "flavor": "Air temple markings with a calm meditative gaze.",
    "iris": "#7f5634",
    "pupil": "#0b0806",
    "eyeWhite": "#f4eadc",
    "outline": "#9b5535",
    "accent": "#3d2018",
    "irisSize": 44,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/tibetan-monk/eyes/left-base.png",
      "rightBase": "assets/skins/tibetan-monk/eyes/right-base.png",
      "thumbnail": "assets/skins/tibetan-monk/thumbnail.png",
      "mask": "assets/skins/tibetan-monk/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1505,
        "y": 0.4656,
        "w": 0.2649,
        "h": 0.2604
      },
      "right": {
        "side": "right",
        "x": 0.5862,
        "y": 0.4656,
        "w": 0.2638,
        "h": 0.2604
      }
    },
    "ambientReactions": [
      "slow-blink",
      "sleepy-idle",
      "look-down",
      "dreamy",
      "idle-long",
      "spacing-out"
    ]
  },
  {
    "id": "alien",
    "name": "Alien",
    "eyeLayout": "dual",
    "flavor": "Bioluminescent skin with an uncanny teal stare.",
    "iris": "#48eed8",
    "pupil": "#020809",
    "eyeWhite": "#dfe8e5",
    "outline": "#627f77",
    "accent": "#142427",
    "irisSize": 40,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/alien/eyes/left-base.png",
      "rightBase": "assets/skins/alien/eyes/right-base.png",
      "thumbnail": "assets/skins/alien/thumbnail.png",
      "mask": "assets/skins/alien/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.04,
        "y": 0.2514,
        "w": 0.354,
        "h": 0.4791
      },
      "right": {
        "side": "right",
        "x": 0.6065,
        "y": 0.2525,
        "w": 0.354,
        "h": 0.4746
      }
    },
    "ambientReactions": [
      "wide-stare",
      "confused",
      "dizzy",
      "cross-eyed",
      "peek",
      "stoned",
      "spacing-out"
    ]
  },
  {
    "id": "hacker",
    "name": "Hacker",
    "eyeLayout": "dual",
    "flavor": "Dark hood, terminal glow, and sharp focus.",
    "iris": "#58ff37",
    "pupil": "#010502",
    "eyeWhite": "#e5e1d8",
    "outline": "#2a2f2b",
    "accent": "#070a09",
    "irisSize": 42,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/hacker/eyes/left-base.png",
      "rightBase": "assets/skins/hacker/eyes/right-base.png",
      "thumbnail": "assets/skins/hacker/thumbnail.png",
      "mask": "assets/skins/hacker/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1466,
        "y": 0.4194,
        "w": 0.2401,
        "h": 0.2413
      },
      "right": {
        "side": "right",
        "x": 0.6082,
        "y": 0.4171,
        "w": 0.239,
        "h": 0.2435
      }
    },
    "ambientReactions": [
      "suspicious",
      "rapid-typing-focus",
      "look-left",
      "look-right",
      "nervous",
      "restless",
      "panic"
    ]
  },
  {
    "id": "anonymous",
    "name": "Anonymous",
    "eyeLayout": "dual",
    "flavor": "White mask, dark hood, and a quiet red stare.",
    "iris": "#ac1220",
    "pupil": "#050203",
    "eyeWhite": "#eee7d7",
    "outline": "#e1ddd1",
    "accent": "#1a1516",
    "irisSize": 34,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/anonymous/eyes/left-base.png",
      "rightBase": "assets/skins/anonymous/eyes/right-base.png",
      "thumbnail": "assets/skins/anonymous/thumbnail.png",
      "mask": "assets/skins/anonymous/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.2063,
        "y": 0.4915,
        "w": 0.2238,
        "h": 0.1781
      },
      "right": {
        "side": "right",
        "x": 0.5722,
        "y": 0.4915,
        "w": 0.2204,
        "h": 0.177
      }
    },
    "ambientReactions": [
      "suspicious",
      "peek",
      "look-left",
      "look-right",
      "idle-long",
      "restless"
    ]
  },
  {
    "id": "ice-hockey",
    "name": "Jason",
    "eyeLayout": "dual",
    "flavor": "Frozen hockey mask with a blood-spattered stare.",
    "iris": "#b82022",
    "pupil": "#05090d",
    "eyeWhite": "#dcecf4",
    "outline": "#ccd7dd",
    "accent": "#101820",
    "irisSize": 38,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/ice-hockey/eyes/left-base.png",
      "rightBase": "assets/skins/ice-hockey/eyes/right-base.png",
      "thumbnail": "assets/skins/ice-hockey/thumbnail.png",
      "mask": "assets/skins/ice-hockey/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1759,
        "y": 0.3224,
        "w": 0.2638,
        "h": 0.2762
      },
      "right": {
        "side": "right",
        "x": 0.5609,
        "y": 0.3224,
        "w": 0.2638,
        "h": 0.2762
      }
    },
    "ambientReactions": [
      "suspicious",
      "angry",
      "furious",
      "wide-stare",
      "shocked",
      "look-left"
    ]
  },
  {
    "id": "clown",
    "name": "Clown",
    "eyeLayout": "dual",
    "flavor": "Cartoon circus face with a bright playful stare.",
    "iris": "#ffcc2e",
    "pupil": "#100711",
    "eyeWhite": "#fff5df",
    "outline": "#ff9aa6",
    "accent": "#590913",
    "irisSize": 38,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/clown/eyes/left-base.png",
      "rightBase": "assets/skins/clown/eyes/right-base.png",
      "thumbnail": "assets/skins/clown/thumbnail.png",
      "mask": "assets/skins/clown/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1528,
        "y": 0.283,
        "w": 0.2599,
        "h": 0.2886
      },
      "right": {
        "side": "right",
        "x": 0.5874,
        "y": 0.283,
        "w": 0.2599,
        "h": 0.2886
      }
    },
    "ambientReactions": [
      "happy",
      "laughing",
      "cross-eyed",
      "dizzy",
      "chaotic-stare",
      "shocked",
      "drunk"
    ]
  },
  {
    "id": "spy",
    "name": "Spy",
    "eyeLayout": "dual",
    "flavor": "Cartoon eyes peeking through newspaper cutouts.",
    "iris": "#4d6f8f",
    "pupil": "#080706",
    "eyeWhite": "#f6f0df",
    "outline": "#d8c7a9",
    "accent": "#4a3c2e",
    "irisSize": 38,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/spy/eyes/left-base.png",
      "rightBase": "assets/skins/spy/eyes/right-base.png",
      "thumbnail": "assets/skins/spy/thumbnail.png",
      "mask": "assets/skins/spy/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1962,
        "y": 0.2694,
        "w": 0.2418,
        "h": 0.2931
      },
      "right": {
        "side": "right",
        "x": 0.5614,
        "y": 0.2728,
        "w": 0.2424,
        "h": 0.2943
      }
    },
    "ambientReactions": [
      "peek",
      "suspicious",
      "look-left",
      "look-right",
      "wide-stare",
      "wink-left",
      "restless"
    ]
  },
  {
    "id": "skeleton",
    "name": "Skeleton",
    "eyeLayout": "dual",
    "flavor": "Playful bone mask with deep skull sockets.",
    "iris": "#f0d36b",
    "pupil": "#07090c",
    "eyeWhite": "#f8f0dc",
    "outline": "#e8dcc2",
    "accent": "#5d5549",
    "irisSize": 38,
    "pupilSize": 18,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/skeleton/eyes/left-base.png",
      "rightBase": "assets/skins/skeleton/eyes/right-base.png",
      "thumbnail": "assets/skins/skeleton/thumbnail.png",
      "mask": "assets/skins/skeleton/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1432,
        "y": 0.175,
        "w": 0.3286,
        "h": 0.5
      },
      "right": {
        "side": "right",
        "x": 0.5271,
        "y": 0.1733,
        "w": 0.3191,
        "h": 0.5
      }
    },
    "ambientReactions": [
      "suspicious",
      "sleepy-idle",
      "shocked",
      "confused",
      "idle-long",
      "spacing-out"
    ]
  },
  {
    "id": "wizard",
    "name": "Wizard",
    "eyeLayout": "dual",
    "flavor": "Moonlit hat, silver brows, and a violet spellcaster gaze.",
    "iris": "#8f6bff",
    "pupil": "#090316",
    "eyeWhite": "#f2e3c5",
    "outline": "#7d5b46",
    "accent": "#2f1b16",
    "irisSize": 42,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/wizard/eyes/left-base.png",
      "rightBase": "assets/skins/wizard/eyes/right-base.png",
      "thumbnail": "assets/skins/wizard/thumbnail.png",
      "mask": "assets/skins/wizard/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.2165,
        "y": 0.478,
        "w": 0.2187,
        "h": 0.3292
      },
      "right": {
        "side": "right",
        "x": 0.571,
        "y": 0.4814,
        "w": 0.2142,
        "h": 0.3224
      }
    },
    "ambientReactions": [
      "dreamy",
      "starstruck",
      "slow-blink",
      "suspicious",
      "spacing-out",
      "wide-stare",
      "wink-right"
    ]
  },
  {
    "id": "cowboy",
    "name": "Cowboy",
    "eyeLayout": "dual",
    "flavor": "Dusty western hat with a curious frontier stare.",
    "iris": "#39b7a3",
    "pupil": "#130a04",
    "eyeWhite": "#fff4df",
    "outline": "#7a421d",
    "accent": "#2f1507",
    "irisSize": 42,
    "pupilSize": 17,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/cowboy/eyes/left-base.png",
      "rightBase": "assets/skins/cowboy/eyes/right-base.png",
      "thumbnail": "assets/skins/cowboy/thumbnail.png",
      "mask": "assets/skins/cowboy/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.208,
        "y": 0.4228,
        "w": 0.2379,
        "h": 0.3923
      },
      "right": {
        "side": "right",
        "x": 0.5524,
        "y": 0.4194,
        "w": 0.2384,
        "h": 0.3968
      }
    },
    "ambientReactions": [
      "suspicious",
      "look-left",
      "look-right",
      "slow-blink",
      "wink-right",
      "restless"
    ]
  },
  {
    "id": "pumpkin-halloween",
    "name": "Pumpkin Halloween",
    "eyeLayout": "dual",
    "flavor": "Glowing jack-o-lantern mischief for spooky notes.",
    "iris": "#95ff24",
    "pupil": "#13020a",
    "eyeWhite": "#fff0bf",
    "outline": "#ff8a12",
    "accent": "#4d1104",
    "irisSize": 42,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/pumpkin-halloween/eyes/left-base.png",
      "rightBase": "assets/skins/pumpkin-halloween/eyes/right-base.png",
      "thumbnail": "assets/skins/pumpkin-halloween/thumbnail.png",
      "mask": "assets/skins/pumpkin-halloween/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.0817,
        "y": 0.3033,
        "w": 0.3083,
        "h": 0.4476
      },
      "right": {
        "side": "right",
        "x": 0.611,
        "y": 0.3055,
        "w": 0.3078,
        "h": 0.4543
      }
    },
    "ambientReactions": [
      "chaotic-stare",
      "shocked",
      "laughing",
      "dizzy",
      "spacing-out",
      "wink-left"
    ]
  },
  {
    "id": "goblin",
    "name": "Goblin",
    "eyeLayout": "dual",
    "flavor": "Green fantasy trouble with a sneaky bright gaze.",
    "iris": "#d6b23a",
    "pupil": "#090704",
    "eyeWhite": "#efe7b8",
    "outline": "#527314",
    "accent": "#192606",
    "irisSize": 42,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/goblin/eyes/left-base.png",
      "rightBase": "assets/skins/goblin/eyes/right-base.png",
      "thumbnail": "assets/skins/goblin/thumbnail.png",
      "mask": "assets/skins/goblin/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1302,
        "y": 0.2875,
        "w": 0.2852,
        "h": 0.4498
      },
      "right": {
        "side": "right",
        "x": 0.5834,
        "y": 0.2897,
        "w": 0.2841,
        "h": 0.4464
      }
    },
    "ambientReactions": [
      "hover-suspicious",
      "suspicious",
      "cross-eyed",
      "laughing",
      "peek",
      "restless"
    ]
  },
  {
    "id": "troll",
    "name": "Troll",
    "eyeLayout": "dual",
    "flavor": "Stone cave face with a heavy grumpy gaze.",
    "iris": "#b7a34f",
    "pupil": "#040b10",
    "eyeWhite": "#d8dbc9",
    "outline": "#4a5b60",
    "accent": "#151d20",
    "irisSize": 40,
    "pupilSize": 16,
    "eyeStyle": {
      "slotRadius": "0px",
      "lidLeft": "-34%",
      "lidWidth": "168%",
      "lidHeight": "122%",
      "lidUpperRadius": "0 0 46% 46%",
      "lidLowerRadius": "46% 46% 0 0"
    },
    "supportsColorOverrides": true,
    "assets": {
      "leftBase": "assets/skins/troll/eyes/left-base.png",
      "rightBase": "assets/skins/troll/eyes/right-base.png",
      "thumbnail": "assets/skins/troll/thumbnail.png",
      "mask": "assets/skins/troll/masks/tab-panel.png"
    },
    "eyeWindows": {
      "left": {
        "side": "left",
        "x": 0.1161,
        "y": 0.31,
        "w": 0.2937,
        "h": 0.3393
      },
      "right": {
        "side": "right",
        "x": 0.5834,
        "y": 0.3191,
        "w": 0.301,
        "h": 0.336
      }
    },
    "ambientReactions": [
      "angry",
      "furious",
      "look-down",
      "sleepy",
      "slow-blink",
      "confused"
    ]
  }
] as const;

export const GENERATED_LAYERED_SKINS = new Set(["robot","cat","manga-female","dragon","cyberpunk-female","c-4po","atlas","panda","d20-rpg","space-helmet","classic-googly","detective-noir","one-eye","tibetan-monk","alien","hacker","anonymous","ice-hockey","clown","spy","skeleton","wizard","cowboy","pumpkin-halloween","goblin","troll"]);

export const GENERATED_SKIN_EYE_WINDOWS = Object.fromEntries(
  GENERATED_SKINS.map((skin) => [skin.id, skin.eyeWindows])
);

export const GENERATED_SKIN_AMBIENT_REACTIONS = Object.fromEntries(
  GENERATED_SKINS.map((skin) => [skin.id, skin.ambientReactions])
);
